### PR TITLE
qml: move OS list fetch to backend

### LINKED ISSUE #714: [BUG] Unable to write custom images / format as FAT32 without Internet
**Describe the bug**

It is no longer possible to write custom images or format as FAT32 without Internet.
As also noticed by end-users: https://forums.raspberrypi.com/viewtopic.php?t=359002

**To Reproduce**

- Disconnect cable or tear down network interface.
- Start Imager
- Press "choose OS"
- Empty screen there

**Additional context**

Imager was originally designed to still offer the option to write a custom .img file, and format as FAT32, even if the user doesn't have Internet and downloading the os_list therefore fails.
This was done by hard coding those options in the osmodel ListModel in main.qml and pre-pending additional items to it on download.

Commit https://github.com/raspberrypi/rpi-imager/commit/3f665e01b40dbf0b9496bb853d6250e7e80af877#diff-6b6066b8c2cfa063e0014db476a9967f054fc913bb71de97644e91e91e3660d3R1400 changes this to only append the custom image options after the OS list is downloaded.
This renders Imager unusable to users that cannot directly use the RPI server for any reason. (Could be no Internet, but also that they are running an old operating system that does not have the right SSL certificates, or that they cannot reach the server directly to firewall problems, which they may have no control over.)

If this change in behavior was intended then at least the commit log should mention that.
Failing that, I consider this a bug.

### PR DESCRIPTION
**Pull request by tdewey-rpi**
- Simple implementation of OS list fetching in backend
- Replace frontend OS list fetching by calls to backend
- OS list updates are brought in asynchronously, avoiding excessive UI blockage.
- "Erase" and "Custom" OS list options are always present, even in a no-internet scenario

Based-On: cillian64/rpi-imager/oslist_backend
Resolves #714

### CODE REVIEW

**Review by cillian64 — APPROVED** [review]

**Comment by maxnet** [comment]
My first thoughts when seeing this code:

- note that we currently use caching for downloads by the qml code. (configured in the networkaccessmanagerfactory)
If the same json file is fetched twice (e.g. because of model change), it is not downloaded twice.
You are creating your own networkaccessmanager objects but I do not see you emabling caching.
Is that intended?

- don't understand the loose functions in anonomous namespace concept. Would be tempted to make them protected class member functions instead, and let them access variables they need like _networkManager directly, instead of passing through function argument.

- not sure if the mutex stuff is strictly necessary.
Imagewriter should be running in same thread as qml/UI.
Stuff we have running in other threads signals main thread through Qt's signal/slot mechanism that posts messages that are read later in main thread's event loop (qt's [queued connection](https://doc.qt.io/qt-6/threads-qobject.html#signals-and-slots-across-threads) method)

**Comment by tdewey-rpi** [comment]
> My first thoughts when seeing this code:
> 
>     * note that we currently use caching for downloads by the qml code. (configured in the networkaccessmanagerfactory)
>       If the same json file is fetched twice (e.g. because of model change), it is not downloaded twice.
>       You are creating your own networkaccessmanager objects but I do not see you emabling caching.
>       Is that intended?

Yes - the intent of this PR is that we're only fetching the various JSON files once per load. I can't see that caching will materially improve that, and would expect JSON servers to perform their own edge caching as is appropriate for their case.

> 
>     * don't understand the loose functions in anonomous namespace concept. Would be tempted to make them protected class member functions instead, and let them access variables they need like _networkManager directly, instead of passing through function argument.

Coding style. I prefer helper functions to _not_ be part of the class, and constrained entirely to the compile unit they're present in.

> 
>     * not sure if the mutex stuff is strictly necessary.
>       Imagewriter should be running in same thread as qml/UI.
>       Stuff we have running in other threads signals main thread through Qt's signal/slot mechanism that posts messages that are read later in main thread's event loop (qt's [queued connection](https://doc.qt.io/qt-6/threads-qobject.html#signals-and-slots-across-threads) method)

When I open rpi-imager in GDB, I'm seeing multiple Qt threads in play, and with the poor documentation around QJson's mutability I decided to not take any chances. Additionally, the QNetworkAccessManager documentation suggests there is parallel activity in play, but doesn't specify the threading model of it's finished() callback:

image

**Comment by tdewey-rpi** [comment]
Latest version of this PR resolves a bug around resolving redirected resullts, and moves the HW filter completely into the backend too. Tried it out in WSL, and it certainly _felt_ snappier, but I've not done any measurement.

File: src/imagewriter.cpp [hunk 1]
```diff
@@ -416,6 +424,212 @@ void ImageWriter::setCustomOsListUrl(const QUrl &url)
...
+                    }
+                } else {
+                    // No devices tags, so work out if we're exclusive or inclusive filtering!
+                    if (inclusive) {
+                        returnArray.append(ositem);
+                    }
+                }
+            }
+
+            //returnArray += ositemObject;
```
Comment (cillian64) [inline src/imagewriter.cpp:583]: Was this line meant to be deleted?

**Comment by maxnet** [comment]
>but doesn't specify the threading model of it's finished() callback

Think you haven't fully discovered the beauty of Qt's signal/slot mechanism yet. Free thread safety. ;-)

It knows when the slot receiver is in a different thread then the signal emitter. (QObjects store thread affinity: https://doc.qt.io/qt-6/qobject.html#thread )
If it is, a call to "emit finished()", will not be processed as a direct callback.
Instead it will post a message to the message loop of the thread of the receiver.
Qt's queued connecting thing.
So your finished() slot will always run in your own thread.

**Comment by tdewey-rpi** [comment]
> > but doesn't specify the threading model of it's finished() callback
> 
> Think you haven't fully discovered the beauty of Qt's signal/slot mechanism yet. Free thread safety. ;-)
> 
> It knows when the slot receiver is in a different thread then the signal emitter. (QObjects store thread affinity: https://doc.qt.io/qt-6/qobject.html#thread ) If it is, a call to "emit finished()", will not be processed as a direct callback. Instead it will post a message to the message loop of the thread of the receiver. Qt's queued connecting thing. So your finished() slot will always run in your own thread.

That's actually a good point! I'll go ahead and drop the Mutexes.

File: src/imagewriter.cpp (hunk 1 above)
Comment (tdewey-rpi) [reply src/imagewriter.cpp:583]: Yes, it was.
